version: '2'

services:
  loadbalancer:
    build:
      context: ./LoadBalancer
      dockerfile: Dockerfile
    depends_on:
      - web
    container_name: loadbalancer

    ports:
    - "8088:6001"
  web:
    build:
      context: ./App
      dockerfile: Dockerfile
    depends_on:
      - db

    ports:
    - "8081-8083:6000"
  db:
    image: mongo:latest
    container_name: db
    environment:
      MONGO_INITDB_DATABASE: Arep
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
    - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    - mongodb:/data/db
    - mongodb_config:/data/configdb
    ports:
    - 27017:27017
    command: mongod
volumes:
  mongodb:
  mongodb_config: